# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:/mapper/**/*.xml #指定mapper.xml路径
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID", ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", ASSIGN_UUID:"全局唯一ID UUID";
      id-type: assign_uuid
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
      logic-delete-field: delFlag
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
  configuration:
    # 只对非嵌套的 resultMap 进行自动映射
    auto-mapping-behavior: partial
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: *
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
  endpoint:
    jmx:
      exposure:
        include: *
    shutdown:
      enabled: true #打开shutdown端点
    info:
      enabled: true
      git:
        mode: simple # full
    health:
      show-details: always  #显示健康具体信息  默认不会显示详细信息

#自定义info端点查看应用相关的信息info:
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

