spring:
  datasource:
    # 配置jdbc 连接
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springauthserver?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 特指 Druid 连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #连接池中允许的最小连接数。缺省值:10
      minimum-idle: 10
      #连接池中允许的最大连接数。缺省值:10
      maximum-pool-size: 20
      #自动提交 默认值为 true
      auto-commit: true
      #连接允许在池中闲置的最长时间，一个连接idle状态的最大时长(毫秒)，超时则被释放(retired)，缺省:18分钟
      idle-timeout: 680080
      #连接池名字，用于日志和监控
      pool-name: mysql-pool
      #一 个连接的生命时长(童秒)，超时而且没被使用则被释放(retired)，缺省:30分钟，建议设置比数据库超时时长少38秒
      max-lifetime: 600080
      #等待连接池分配连接的最大时长(童秒)，超过这个时长还没可用的连接则发生50LException， 缺省:38秒
      connection-timeout: 38000
      #连接测试查询语句，用于验证连接是否有效
      connection-test-query: select 1
      #验证连接有效性的超时时间，单位为秒,默认值 5000 秒(5 秒)
      validation-timeout: 38000
      #设置事务隔离级别,不配置此项默认遵从数据库的配置，读已提交TRANSACTION READ COMMITTED,此外还有读未提交TRANSACTION READ UNCOMMITTED，可重复度TRANSACTION REPEATABLE READ，串行化TRANSACTION SERIALIZABLE
      transaction-isolation: TRANSACTION_READ_COMMITTED
      #是否将连接设置为只读模式，默认false
      readonly: false
